global:
  smtp_from: 'kianyarii1383@gmail.com'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: 'kianyarii1383@gmail.com'
  smtp_auth_password: 'vwzxxzofvpjnryef'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'kianyarii1383@gmail.com'
    send_resolved: true
