global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '185.252.86.8:9093'
    scheme: http

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'website'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['freediscussion.liara.run']
    scheme: https
