global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['localhost:8000'] # Replace with your Django server address and port