# Generated by Django 5.1.2 on 2024-11-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
