# Generated by Django 5.1.2 on 2024-11-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_tempuser_otp_delete_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
