# Generated by Django 5.1.2 on 2024-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_tempuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
