# Generated by Django 5.1.2 on 2024-11-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_tempuser_email_alter_tempuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='a1', max_length=2),
        ),
    ]
