# Generated by Django 5.1.2 on 2024-12-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_image'),
        ('authentication', '0003_alter_tempuser_otp'),
    ]

    operations = [
    ]
