# Generated by Django 5.1.2 on 2024-11-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_city_user_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
