# Generated by Django 5.1.2 on 2024-11-15 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pending_members',
            field=models.ManyToManyField(related_name='pending_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
