# Generated by Django 5.1.2 on 2024-11-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
    ]
