name: CD

on:
  push:
    branches:
      - fix/sprint_issues
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Pull latest images
          docker-compose pull
          
          # Stop existing containers
          docker-compose down
          
          # Start containers
          docker-compose up -d