name: CD

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/kianyari/web:latest .
        docker push ghcr.io/kianyari/web:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Pull latest image
          docker pull ghcr.io/kianyari/web:latest
          
          # Stop and remove existing containers
          docker stop web celery-worker celery-beat || true
          docker rm web celery-worker celery-beat || true
          
          # Start web container
          docker run -d --name web \
            -p 8000:8000 \
            ghcr.io/kianyari/web:latest
          
          # Start Celery worker container
          docker run -d --name celery-worker \
            ghcr.io/kianyari/web:latest \
            celery -A FD worker --loglevel=info
          
          # Start Celery beat container
          docker run -d --name celery-beat \
            ghcr.io/kianyari/web:latest \
            celery -A FD beat --loglevel=info
