name: CD

on:
  push:
    branches:
      - fix/sprint_issues
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and Push Docker Image
      run: |
        docker-compose build
        docker-compose push

    - name: Prepare deployment files
      run: |
        tar -czf deployment.tar.gz docker-compose.yml .env

    - name: Copy files and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Create necessary directories
          mkdir -p /home/fd
          
          # Copy deployment files
          scp ${{ github.workspace }}/deployment.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/fd/
          
          # Extract files
          cd /home/fd
          tar -xzf deployment.tar.gz
          
          # Set correct permissions
          chmod 644 /home/fd/.env
          
          # Pull latest images
          sudo docker-compose pull
          
          # Stop existing containers
          sudo docker-compose down
          
          # Start containers
          sudo docker-compose up -d
          
          # Clean up
          rm deployment.tar.gz