name: CD

on:
  push:
    branches:
      - fix/sprint_issues
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and Push Docker Image
      run: |
        docker-compose build
        docker-compose push

    - name: Copy files and deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |

          cd ../home/fd
          
          echo "${{ secrets.ENV_FILE }}" > .env
          
          scp ${{ github.workspace }}/docker-compose.yml docker-compose.yml
          scp ${{ github.workspace }}/prometheus.yml prometheus.yml
          scp ${{ github.workspace }}/alert_rules.yml alert_rules.yml
          scp ${{ github.workspace }}/alertmanager.yml alertmanager.yml

          chmod 644 .env

          sudo docker-compose pull
          
          sudo docker-compose down
          
          sudo docker-compose up -d