name: CI/CD

on:
  push:
    branches:
      - feat/CI/CD
  pull_request:
    branches:
      - develop
  pull_request_target:
    types:
      - closed

jobs:
  test:
    #if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Write .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
      run: |
        python manage.py test --keepdb

  deploy:
    #if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/kianyari/web:latest .
        docker push ghcr.io/kianyari/web:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull ghcr.io/<YOUR_GITHUB_USERNAME>/<YOUR_REPO_NAME>:latest
          docker stop <YOUR_CONTAINER_NAME> || true
          docker rm <YOUR_CONTAINER_NAME> || true
          docker run -d --name <YOUR_CONTAINER_NAME> -p 8000:8000 ghcr.io/<YOUR_GITHUB_USERNAME>/<YOUR_REPO_NAME>:latest
